### ISSUE TITLE
error parsing kwl due to "invalid syntax"

### ISSUE THREAD

**Issue by 4evertutelary** [google/battery-historian#112]
When a kwl's name contained ",", such as:
800f000.qcom,spmi:qcom,pm8998@0:qcom,pm8998_rtc
Battery-historian will failed to parse it.

Checkin batterystats for refrence.
------ CHECKIN BATTERYSTATS (dumpsys -t 30 batterystats -c) ------
…
9,0,l,kwl,800f000.qcom,spmi:qcom,pm8998@0:qcom,pm8998_rtc,11,6,-1,-1

**Comment by 4evertutelary** [comment]
More log for reference:

2017/04/18 17:35:12 parseSystemKernelWakelock ["ipc0000005e_ssuiccd" "6" "14" "-1" "-1"]
2017/04/18 17:35:12 parseSystemKernelWakelock ["ipc00000076_netmgrd" "0" "0" "-1" "-1"]
2017/04/18 17:35:12 parseSystemKernelWakelock ["800f000.qcom" "spmi:qcom" "pm8998@0:qcom" "pm8998_rtc" "11" "6" "-1" "-1"]

**Comment by sshept2** [comment]
I had the same problem. But I solved the problem.
9,0,l,kwl,800f000.qcom,spmi:qcom,pm8998@0:qcom,pm8998_rtc,11,6,-1,-1
→9,0,l,kwl,"800f000.qcom,spmi:qcom,pm8998@0:qcom,pm8998_rtc",11,6,-1,-1
that`all

**Comment by sshept2** [comment]
If it is solved, please answer
