### ISSUE TITLE
Could not parse aggregated battery stats.

### ISSUE THREAD

**Issue by sshept2** [google/battery-historian#118]
I found the following error when using battery historian

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

The underlying format for kwl has 3 additional field(s) that are not captured.

error parsing kwl: strconv.ParseFloat: parsing "spmi:qcom": invalid syntax
error parsing kwl: strconv.ParseFloat: parsing "pm8998@0:qcom": invalid syntax
error parsing kwl: strconv.ParseInt: parsing "pm8998_rtc": invalid syntax

Does anyone know how to fix it?

**Comment by NNickey** [comment]
More information needs to be provided like a bug report, or screenshots of the error, any warnings/errors, and anything in your browsers 'dev console'.

**Comment by sshept2** [comment]
This is part of the bug report

9,0,l,kwl,ipc000000e4_netmgrd,0,0,-1,-1
9,0,l,kwl,ipc0000010e_system_server,0,0,-1,-1
9,0,l,kwl,ipc0000008a_netmgrd,0,13,-1,-1
9,0,l,kwl,800f000.qcom,spmi:qcom,pmi8998@2:qpnp,fg,0,0,-1,-1
9,0,l,kwl,ipc0000005a_ssuiccd,0,0,-1,-1
9,0,l,kwl,ipc00000086_netmgrd,0,0,-1,-1

Bug reports can not be uploaded due to security concerns 
Do you have any other necessary information?

**Comment by sshept2** [comment]
here is part of bugreport

9,0,l,kwl,ipc0000003a_kworker/4:6,0,0,-1,-1
9,0,l,kwl,ipc00000049_kworker/u16:2,0,0,-1,-1
9,0,l,kwl,800f000.qcom,spmi:qcom,pm8998@0:qcom,pm8998_rtc,0,0,-1,-1
9,0,l,kwl,ipc000000a2_netmgrd,0,0,-1,-1
9,0,l,kwl,ipc00000046_kworker/u16:6,0,1,-1,-1
9,0,l,kwl,msm_amrwbplus,0,0,-1,-1

I can not uploaded bugreport because security problems
Have any necessary informations?

**Comment by kwadkore** [comment]
800f000.qcom,spmi:qcom,pm8998@0:qcom,pm8998_rtc needs to be surrounded in quotes. Without the quotes, parsing as CSV separates that part of the line into 4 separate entries, which violates the expected kwl line format.

**Comment by sshept2** [comment]
I solved the problem. Thank you very much!!!
