### ISSUE TITLE
Run Battery Historian command is not working

### ISSUE THREAD

**Issue by mzq729019** [google/battery-historian#119]
In the README.md, you guys say run the command below after install Docker

`docker -- run -p <port>:9999 gcr.io/android-battery-historian:2.1 --port 9999`

But it's not working in my case, Docker version 17.03.1-ce, build c6d412e 

Instead, the following command works

`docker run -p <port>:9999 gcr.io/android-battery-historian:2.1 --port 9999`

**Comment by IvRRimum** [comment]
Doesn't work for me, this is what i execute:

`docker run -p 9999:9999 gcr.io/android-battery-historian/stable:3.0 --port 9999`

**Comment by hpbl** [comment]
I keep getting this, even though I have logged in:

```
Unable to find image 'gcr.io/android-battery-historian/stable:3.0' locally
docker: Error response from daemon: pull access denied for gcr.io/android-battery-historian/stable, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

can anyone help?

**Comment by siltus** [comment]
I have same issue as @hpbl

**Comment by limone-eth** [comment]
i also have the same issue

**Comment by amsterdatech** [comment]
I've found an workaround and commented at
https://github.com/google/battery-historian/issues/125
