### ISSUE TITLE
Android Wear Oreo bugreports cannot be parsed.

### ISSUE THREAD

**Issue by matejdro** [google/battery-historian#136]
Bugreports created by Android Wear watches running Oreo (only LG Watch Sport beta at the moment) are not parsed. Following error shows:

```
strconv.ParseFloat: parsing "p": invalid syntax
could not parse aggregated battery stats
device capacity is 0
```

Example bugreport: https://drive.google.com/file/d/0B2kGIGhRh2jLS0pwQVc4X2RSbVU/view?usp=sharing (shared with android-bugreport@google.com)

**Comment by matejdro** [comment]
Ignore that, I had old historian build.

**Comment by adam-mark** [comment]
How did you solve this problem?

**Comment by matejdro** [comment]
I just updated to latest battery historian and it went away.

**Comment by adam-mark** [comment]
I am using docker to run the battery historian and I don't  know how to update to the latest version... :(
