### ISSUE TITLE
Errors Parsing Device Dumps

### ISSUE THREAD

**Issue by devunwired** [google/battery-historian#15]
Using an Android 5.0.1 test device (or emulator) the following steps will create a stats dump that historian will crash on parsing (steps are per the header comments in the script):
- `adb shell dumpsys batterystats --enable full-wake-history`
- ` adb shell dumpsys batterystats --reset`
- Swipe around launcher for a few seconds
- `adb shell dumpsys batterystats > outfile.txt`

Attempting to parse the above file with `historian outfile.txt` produces the following crash:
```
Traceback (most recent call last):
  File "~/bin/historian", line 1247, in <module>
    main()
  File "~/bin/historian", line 1050, in main
    legacy_mode = is_file_legacy_mode(input_file)
  File "~/bin/historian", line 231, in is_file_legacy_mode
    line_time = line.split()[0]
IndexError: list index out of range
```

Additionally, historian cannot parse a stats dump generated for a single process. Steps to reproduce:
- `adb shell dumpsys batterystats --enable full-wake-history`
- ` adb shell dumpsys batterystats --reset`
- Launch browser and use for a short while
- `adb shell dumpsys batterystats com.android.browser > outfile.txt`

Attempting to parse the above file with `historian outfile.txt` hangs the script as it blocks waiting for more input. It looks as though this is because the per-process dump does not have the "Battery History" header that historian is hard-coded to look for.

Here is a link to a gist with sample dumps of both conditions: https://gist.github.com/devunwired/e8d240d1f00a30c060cd

From the header comments, it may be that the tools is not meant to handle output directly from `dumpsys batterystats`, however from the SDK site this is not clear (https://developer.android.com/about/versions/android-5.0.html#Power). In that event, the fix to this may instead just be more graceful error handling (i.e. "you're using the wrong file dummy, do this instead...") rather than hanging or crashing. A more explicit README on this project might help to document the proper uses as well.

**Comment by efi-mk** [comment]
@devunwired did you manage to run it eventually on a single app ?

**Comment by peastham** [comment]
The script is meant to take a whole bugreport ("adb bugreport"), the sdk
docs are wrong.  You're right though, it should be more resilient.

**Comment by peastham** [comment]
I wasn't able to reproduce the crash, but I just hardened the code -- see if it helps.  If not, please upload a failing data file.  

Also, I added support for handling output from dumpsys, but single process output is not planned to be supported.
