### ISSUE TITLE
Graph not drawn, many parsing errors

### ISSUE THREAD

**Issue by galex** [google/battery-historian#21]
Hello, 

Thank you for updating the tool! It looks amazing! 
I just tried it on a bug report from an Nexus 5 with Android M Preview and got many errors. 

Bug report and errors here: https://drive.google.com/folderview?id=0B5t6EcjJ36rvflJLYkZnRmctQ2JCSFRXY05zdW15eUl2YjVVQ0tkRXZBNGRWQktkT2l5WVk&usp=sharing

Regards,
Alex

**Comment by changchingchi** [comment]
hello, is there any updates, how did you fix it? I am facing the same issue.

**Comment by kwadkore** [comment]
Those errors just indicate that Historian didn't know how to parse some data in the history. The update that went out yesterday should address those.
