### ISSUE TITLE
stat exec/local_checkin_parse.go: no such file or directory

### ISSUE THREAD

**Issue by sleekweasel** [google/battery-historian#23]
The battery historian server is working, but the other command-line tools don't work, as shown above.

Are the docs out of date?

I tried running go run cmd/checkin-parse/local_checkin_parse.go --input=$HOME/bugreport.txt but got this output:

# command-line-arguments
cmd/checkin-parse/local_checkin_parse.go:49: undefined: batterystats.Checkin
cmd/checkin-parse/local_checkin_parse.go:50: undefined: parse
cmd/checkin-parse/local_checkin_parse.go:55: undefined: parse
cmd/checkin-parse/local_checkin_parse.go:56: undefined: parse
cmd/checkin-parse/local_checkin_parse.go:66: undefined: parse
cmd/checkin-parse/local_checkin_parse.go:71: undefined: parse
cmd/checkin-parse/local_checkin_parse.go:80: undefined: parse
cmd/checkin-parse/local_checkin_parse.go:88: undefined: parse
cmd/checkin-parse/local_checkin_parse.go:91: undefined: parse
cmd/checkin-parse/local_checkin_parse.go:91: too many errors

Ta

**Comment by kwadkore** [comment]
Incorrect links in the code. Should be fixed now.
