### ISSUE TITLE
My App Mobile radio (active) time per app rank 0

### ISSUE THREAD

**Issue by lizijin** [google/battery-historian#27]
Hello,I used battery historian to analyze my app's battery usage .I found that the Mobile radio (active) time per app  rank 0  in all apps .  Anyone can tell me what  result this .Thanks in advance.
<img width="945" alt="2015-07-06 10 23 34" src="https://cloud.githubusercontent.com/assets/1308769/8514778/1f5a3456-23c9-11e5-8372-20fb21fcca8b.png">

**Comment by kwadkore** [comment]
Rank 0 just means that the app has the highest mobile active time amongst all apps in the report.
