### ISSUE TITLE
Parsing errors with blank system stats page

### ISSUE THREAD

**Issue by matejdro** [google/battery-historian#34]
![screenshot](https://cloud.githubusercontent.com/assets/507922/10029403/fd0caca8-6171-11e5-8a0a-9000b8921c20.png)

This started happening with dumps from my phone after upgrading to Android 5.1.1.Historian 2.0 tab (graph one) is fine, but System Stats and App Stats are empty.

Example bugreport that causes this: https://drive.google.com/file/d/0B2kGIGhRh2jLOGFnOW55LTlGcUk/view?usp=sharing

**Comment by lubeast** [comment]
![battery](https://cloud.githubusercontent.com/assets/3817355/13482292/07a45fb4-e127-11e5-8569-918b9ae9c260.png)

Same issue with you. `Android 5.1.1`
Does anyone know why or how to solve it?

**Comment by kwadkore** [comment]
I'm not able to view the linked bug report, but the error shown is that Historian saw two misc lines in the report. The recent update to Historian should address this.
