### ISSUE TITLE
Battery Historian - Setup Issue

### ISSUE THREAD

**Issue by farhan-arbisoft** [google/battery-historian#35]
When i run following command on my windows machine (OS Windows 10) given in setup.

// Compile Javascript files using the Closure compiler
$ bash setup.sh

It gives the following result and i am unable to do a proper setup for battery historian.
C:\Users\USERNAME\go_work\src\github.com\google\battery-historian>bash setup.sh
setup.sh: line 58: java: command not found

I tried the mentioned line command into command prompt directly but didn't work either.

Command given on line 58 is:
java -jar third_party/closure-compiler/compiler.jar --closure_entry_point historian.Historian \
      --js js/*.js \
      --js third_party/closure-library/closure/goog/base.js \
      --js third_party/closure-library/closure/goog/** \
      --only_closure_dependencies \
      --generate_exports \
      --js_output_file compiled/historian-optimized.js \
      --compilation_level SIMPLE_OPTIMIZATIONS

If someone can help me in fixing it, it would be great.
Need this tool in urgent.

**Comment by ph0b** [comment]
Hi, 

You need to have Java installed and java.exe added to your PATH environment variable (or use it by specifying its absolute path).

I think you should use backslashes for the call to Java too:

java -jar third_party\closure-compiler\compiler.jar --closure_entry_point historian.Historian --js js\*.js --js third_party\closure-library\closure\goog\base.js --js third_party\closure-library\closure\goog\** --only_closure_dependencies --generate_exports --js_output_file compiled\historian-optimized.js --compilation_level SIMPLE_OPTIMIZATIONS

I've written a more detailed guide on installing battery historian on Windows, you can find it here: http://ph0b.com/battery-historian-2-0-windows/

**Comment by farhan-arbisoft** [comment]
Hi,

It worked perfectly.
Thanks! and try to put this windows setup url on start of Hisotrian documentation so that windows users follow this one.

**Comment by farhan-arbisoft** [comment]
Hi,

     thanks for collaboration, just one quick question.

What does that Computed power drain means in 'App Stats' tab of generated
web page.
During testing of my app its value is 0.90%. What does that acually mean?

And if some tutorial or description is available about Historian 2.0 that
would be great help.

On Sat, Oct 3, 2015 at 11:25 AM, Xavier Hallade <notifications@github.com>
wrote:

> Hi,
>
> You need to have Java installed and java.exe added to your PATH
> environment variable (or use it by specifying its absolute path).
>
> I think you should use backslashes for the call to Java too:
>
> java -jar third_party\closure-compiler\compiler.jar --closure_entry_point
> historian.Historian --js js*.js --js
> third_party\closure-library\closure\goog\base.js --js
> third_party\closure-library\closure\goog** --only_closure_dependencies
> --generate_exports --js_output_file compiled\historian-optimized.js
> --compilation_level SIMPLE_OPTIMIZATIONS
>
> I've written a more detailed guide on installing battery historian on
> Windows, you can find it here:
> http://ph0b.com/battery-historian-2-0-windows/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/battery-historian/issues/35#issuecomment-145209660>
> .
>



-- 
*--------*
Regards,

Muhammad Farhan Khan
Senior Software Engineer

Arbisoft (Pvt.) Ltd.
www.arbisoft.com
