### ISSUE TITLE
Error generating historian plot: fork/exec ./historian.py: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by Gaurav504** [google/battery-historian#37]
Hi,

I have generated the bug report for kitkat and below OS with adb command.

But after uploading the file it shows this error 'Error generating historian plot: fork/exec ./historian.py: %1 is not a valid Win32 application.'.

Any suggestions.

Working fine for the bugreports taken for Lollipop devices.

Thanks in advance
Gaurav

**Comment by farhan-arbisoft** [comment]
I was experiencing same kind of issue on windows machine.

But this tutorial helped me  http://ph0b.com/battery-historian-2-0-windows/

Read following section in this url. I copied from url page. Might help you.
I need to see the GPS stats used by any app. Would be great help to know if
you are doing it. :)
-------------------

While we’re editing sources, if you want the Battery Historian 1.0 tab to
work from Battery Historian 2.0, change line 266 of
*battery-historian\analyzer\analyzer.go* to add first the reference to your
Python executable (python.exe is enough if the directory is part of your
path):

diff
1
2
-       cmd := exec.Command("./historian.py", "-c", "-m", "-r", reportName,
filepath)
+       cmd := exec.Command("C:\\Python27\\python.exe", "./historian.py",
"-c", "-m", "-r", reportName, filepath)

On Thu, Oct 8, 2015 at 5:10 PM, Gaurav504 <notifications@github.com> wrote:

> Hi,
>
> I have generated the bug report for kitkat and below OS with adb command.
>
> But after uploading the file it shows this error 'Error generating
> historian plot: fork/exec ./historian.py: %1 is not a valid Win32
> application.'.
>
> Any suggestions.
>
> Working fine for the bugreports taken for Lollipop devices.
>
> Thanks in advance
> Gaurav
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/battery-historian/issues/37>.
>



-- 
*--------*
Regards,

Muhammad Farhan Khan
Senior Software Engineer

Arbisoft (Pvt.) Ltd.
www.arbisoft.com

**Comment by Gaurav504** [comment]
I already tried it.
It is not working with this.

**Comment by Gaurav504** [comment]
My major concern is whether bugreports taken for Jelley Bean/kitkat can be converted in html with this tool?

**Comment by farhan-arbisoft** [comment]
Not sure about these versions but for Lollipop and above its working fine!

On Fri, Oct 9, 2015 at 12:03 PM, Gaurav504 <notifications@github.com> wrote:

> My major concern is whether bugreports taken for Jelley Bean/kitkat can be
> converted in html with this tool?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/battery-historian/issues/37#issuecomment-146773749>
> .
>



-- 
*--------*
Regards,

Muhammad Farhan Khan
Senior Software Engineer

Arbisoft (Pvt.) Ltd.
www.arbisoft.com

**Comment by leiwuyue** [comment]
HI :
for Lollipop 
 I had this question also, but according to   http://ph0b.com/battery-historian-2-0-windows/
now ,click "system stats" or  "historian 2.0" or  "APP stats" ,it works ok ,

but when click "historian(legacy)" ,it still exists the quesiong    Please wait, drawing chart...
Error generating historian plot: fork/exec ./historian.py: %1 is not a valid Win32 application.

when mouse is on "historian(legacy)" , it tips data visualization for history stats,version 1。 Is it maybe the version is not version 2 ? I do not why?   my env is win7 32  ,python2.7 .
Can give any help ? thanks.

**Comment by q88535448** [comment]
you just need to run "go run cmd\battery-historian\battery-historian.go" again after modify  cmd := exec.Command("C:\\Python27\\python.exe", "./historian.py",
"-c", "-m", "-r", reportName, filepath). Then your problem will be done.

**Comment by kwadkore** [comment]
Please try with the updated version.
