### ISSUE TITLE
Setup broken

### ISSUE THREAD

**Issue by bobobo1618** [google/battery-historian#42]
Running `go get -u github.com/google/battery-historian` fetches the Historian code but fails to fetch dependencies:

```
package github.com/google/battery-historian
	imports github.com/google/battery-historian
	imports github.com/google/battery-historian: no buildable Go source files in /home/historian/Go/src/github.com/google/battery-historian
```

Running `setup.sh` gives me (among other things), this:

```
third_party/closure-library/closure/goog/base_module_test.html:1: ERROR - Parse error. primary expression expected
<!DOCTYPE html>
 ^

third_party/closure-library/closure/goog/base_test.html:1: ERROR - Parse error. primary expression expected
<!DOCTYPE html>
 ^

third_party/closure-library/closure/goog/defineclass_test.html:1: ERROR - Parse error. primary expression expected
<!DOCTYPE html>
 ^

3 error(s), 21 warning(s
```

Compilation of tests seems to be the issue as running `rm third_party/closure-library/closure/goog/*_test.html` beforehand results in successful compilation.

**Comment by jinksw** [comment]
I have this issue too. and after I ignore this I can still start the server bug no matter what file I upload.It comes the error page.

Battery Historian 2.0

Device: unknown device 
Analyze a new bugreport. 
Parsing Errors:Hide
unsupported bug report version
unable to find device SDK version
Please wait, drawing chart...

**Comment by tBi2rcAlKQlG** [comment]
Same issue on Windows 10.  I deleted base_module_test.html, base_test.html, and defineclass_test.html and was able to complete the compilation and get it to work.

**Comment by Tuxdude** [comment]
I'm running into the same issue on OSX. If I ignore this error, I'm able to start the Historian server, but it does not seem to display any of the charts in Historian Legacy pane when loading bugreports. Historian 2.0 pane output is completely blank always.

**Comment by thelinuxmaniac** [comment]
I too have the same error on Ubuntu 14.04 "

```
$ go get -u github.com/google/battery-historian
package github.com/google/battery-historian: no buildable Go source files in /home/duttaa/mybin/google/go/src/github.com/google/battery-historian
```

```
.../src/github.com/google/battery-historian$ bash setup.sh 
third_party/closure-library/closure/goog/base_module_test.html:3: WARNING - Parse error. In some cases, '<!--' and '-->' are treated as a '//' for legacy reasons. Removing this from your code is safe for all browsers currently in use.
<!--
^

third_party/closure-library/closure/goog/base_module_test.html:8: WARNING - Parse error. In some cases, '<!--' and '-->' are treated as a '//' for legacy reasons. Removing this from your code is safe for all browsers currently in use.
-->
^

third_party/closure-library/closure/goog/base_test.html:3: WARNING - Parse error. In some cases, '<!--' and '-->' are treated as a '//' for legacy reasons. Removing this from your code is safe for all browsers currently in use.
<!--
^

third_party/closure-library/closure/goog/base_test.html:8: WARNING - Parse error. In some cases, '<!--' and '-->' are treated as a '//' for legacy reasons. Removing this from your code is safe for all browsers currently in use.
-->
^

third_party/closure-library/closure/goog/defineclass_test.html:3: WARNING - Parse error. In some cases, '<!--' and '-->' are treated as a '//' for legacy reasons. Removing this from your code is safe for all browsers currently in use.
<!--
^

third_party/closure-library/closure/goog/defineclass_test.html:8: WARNING - Parse error. In some cases, '<!--' and '-->' are treated as a '//' for legacy reasons. Removing this from your code is safe for all browsers currently in use.
-->
^

third_party/closure-library/closure/goog/base_module_test.html:1: ERROR - Parse error. primary expression expected
<!DOCTYPE html>
 ^

third_party/closure-library/closure/goog/base_test.html:1: ERROR - Parse error. primary expression expected
<!DOCTYPE html>
 ^

third_party/closure-library/closure/goog/defineclass_test.html:1: ERROR - Parse error. primary expression expected
<!DOCTYPE html>
 ^

3 error(s), 6 warning(s)
```

**Comment by goncalossilva** [comment]
Same issue on OSX. Charts are absent even after deleting the broken test files.

**Comment by jayhou** [comment]
same issue on Ubuntu, but still can run the "go run cmd/battery-historian/battery-historian.gon" command to start the web server, but the "Hitorian 2.0" TAB is nothing present, I don't know if cause by the setup errors.

**Comment by jocelyndang** [comment]
Thanks for letting us know - we have a fix we're hoping to push out by the end of this week.

**Comment by dvdh** [comment]
Having similar symptoms as jayhou above, this is the error for the setup phase
$ bash setup.sh 
ERROR - required entry point "historian.Historian" never provided

1 error(s), 0 warning(s)

**Comment by spongebobrf** [comment]
Same issue here : 
bash setup.sh
ERROR - required entry point "historian.Historian" never provided

1 error(s), 0 warning(s)

**Comment by jocelyndang** [comment]
This seems to have been affected by a recent Closure compiler change - please try the latest patch, and use
bash setup.sh --rebuild_all
so it'll remove the previously downloaded version.

Let us know how it goes!

**Comment by albertchristian92** [comment]
I am already use setup.sh --rebuild_all

but it still have same error

http://prntscr.com/a3w69g

**Comment by bobobo1618** [comment]
After doing a clean pull of the repository, everything is working perfectly, thanks!

**Comment by albertchristian92** [comment]
I am still new user actually, can you help me to explain what you means clean pull of the repository? I am not understand. thanks anyway.

**Comment by lubeast** [comment]
same issue with @Tuxdude . Does anybody know how to solve it?
