### ISSUE TITLE
newer report version 15 found

### ISSUE THREAD

**Issue by ozaryx** [google/battery-historian#49]
On Android 6.0

Warnings:Hide
newer report version 15 found
The underlying format for kwl has 1 additional field(s) that are not captured.

**Comment by bobobo1618** [comment]
The Nexus 5X on build MMB29P seems to output reports with this version that consistently show this warning and break the display. Even the aggregated stats aren't displayed.

**Comment by kwadkore** [comment]
Harmless warning to indicate that battery information has been updated in the bug report. The recent Battery Historian update covers version 15.
