### ISSUE TITLE
unknown key

### ISSUE THREAD

**Issue by ozaryx** [google/battery-historian#50]
On Android 6.0

** Error in 9,h,0,Bl=84,Bs=c,Bh=g,Bp=a,Bt=345,Bv=4195,+r,+w,+Wm,+Wr,+S,+BP,Pss=3,Sb=1,+Ww,+W,+ch,Wss=4,Wsp=compl in  +Ww : unknown key Ww. ** Error in 9,h,0,Bl=84,Bs=c,Bh=g,Bp=a,Bt=345,Bv=4195,+r,+w,+Wm,+Wr,+S,+BP,Pss=3,Sb=1,+Ww,+W,+ch,Wss=4,Wsp=compl in  +ch : unknown key ch. 
** Error in 9,h,17,Est=72 in  Est=72 : unknown key Est. 
** Error in 9,h,2,Est=75 in  Est=75 : unknown key Est. 
** Error in 9,h,7,Bp=n,Bt=368,Bv=8424,-BP,-ch,+Ewl=77 in  -ch : unknown key ch. 
** Error in 9,h,110,-Wm,Est=95 in  Est=95 : unknown key Est. 
** Error in 9,h,9973,Bt=344,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,724,+Eal=99 in  +Eal=99 : unknown key Eal. 
** Error in 9,h,1,+Wr,+Etw=100 in  +Etw=100 : unknown key Etw. 
** Error in 9,h,11,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,6,-Eal=99 in  -Eal=99 : unknown key Eal. 
** Error in 9,h,7011,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1719,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,4082,+r,-Etw=100 in  -Etw=100 : unknown key Etw. 
** Error in 9,h,2128,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1473,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,21311,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1171,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,6018,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1952,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,11266,Bt=326,+r,+Eal=102 in  +Eal=102 : unknown key Eal. 
** Error in 9,h,8,+Eal=103 in  +Eal=103 : unknown key Eal. 
** Error in 9,h,9,-Eal=102 in  -Eal=102 : unknown key Eal. 
** Error in 9,h,4,-Eal=103 in  -Eal=103 : unknown key Eal. 
** Error in 9,h,152,+Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,30,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,600,+Eal=114 in  +Eal=114 : unknown key Eal. 
** Error in 9,h,2,-Eal=114 in  -Eal=114 : unknown key Eal. 
** Error in 9,h,10633,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,31,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,5988,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,2146,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,455,+Eal=117 in  +Eal=117 : unknown key Eal. 
** Error in 9,h,1,+Eal=118 in  +Eal=118 : unknown key Eal. 
** Error in 9,h,2,+Eal=102 in  +Eal=102 : unknown key Eal. 
** Error in 9,h,0,+Eal=119 in  +Eal=119 : unknown key Eal. 
** Error in 9,h,2,-Eal=117 in  -Eal=117 : unknown key Eal. 
** Error in 9,h,1,-Eal=118 in  -Eal=118 : unknown key Eal. 
** Error in 9,h,8,-Eal=102 in  -Eal=102 : unknown key Eal. 
** Error in 9,h,21,-Eal=119 in  -Eal=119 : unknown key Eal. 
** Error in 9,h,4038,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,721,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,5798,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,949,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,6305,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,757,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,6541,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,25,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,13217,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,211,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,6323,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1068,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,6041,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,2220,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,1,+Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,14432,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,0,Dcpu=12230:45830 in  Dcpu=12230:45830 : unknown key Dcpu. 
** Error in 9,h,0,Dpst=13580,44740,8430,0,1170,78310 in  Dpst=13580 : unknown key Dpst. ** Error in 9,h,0,Dpst=13580,44740,8430,0,1170,78310 in  44740 : unknown key 44740. ** Error in 9,h,0,Dpst=13580,44740,8430,0,1170,78310 in  8430 : unknown key 8430. ** Error in 9,h,0,Dpst=13580,44740,8430,0,1170,78310 in  0 : unknown key 0. ** Error in 9,h,0,Dpst=13580,44740,8430,0,1170,78310 in  1170 : unknown key 1170. ** Error in 9,h,0,Dpst=13580,44740,8430,0,1170,78310 in  78310 : unknown key 78310. 
** Error in 9,h,17,-r,Est=127 in  Est=127 : unknown key Est. 
** Error in 9,h,1080,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,6588,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,691,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,8745,+r,+Eal=102 in  +Eal=102 : unknown key Eal. 
** Error in 9,h,4,+Eal=128 in  +Eal=128 : unknown key Eal. 
** Error in 9,h,1,+Etw=129 in  +Etw=129 : unknown key Etw. 
** Error in 9,h,13,-Eal=102 in  -Eal=102 : unknown key Eal. 
** Error in 9,h,5,-Eal=128 in  -Eal=128 : unknown key Eal. 
** Error in 9,h,2,+Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,6021,+r,-Wr,-Etw=129 in  -Etw=129 : unknown key Etw. 
** Error in 9,h,44,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1862,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,6998,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,426,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,944,+r,+Eal=132 in  +Eal=132 : unknown key Eal. 
** Error in 9,h,1,-Eal=132 in  -Eal=132 : unknown key Eal. 
** Error in 9,h,2,+Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,12659,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1213,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,1007,+r,+Eal=133 in  +Eal=133 : unknown key Eal. 
** Error in 9,h,5,+Etw=134 in  +Etw=134 : unknown key Etw. 
** Error in 9,h,22,-Eal=133 in  -Eal=133 : unknown key Eal. 
** Error in 9,h,8861,+r,+Eal=102 in  +Eal=102 : unknown key Eal. 
** Error in 9,h,9,+Eal=119 in  +Eal=119 : unknown key Eal. 
** Error in 9,h,1,-Eal=102 in  -Eal=102 : unknown key Eal. 
** Error in 9,h,42,-Eal=119 in  -Eal=119 : unknown key Eal. 
** Error in 9,h,534,-Etw=134 in  -Etw=134 : unknown key Etw. 
** Error in 9,h,2565,-Ws,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,5530,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,19139,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,404,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,6249,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1606,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,5784,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1320,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,7110,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,544,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,6065,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1527,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,5933,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1411,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,24943,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,720,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,6429,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1913,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,6054,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1218,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,20449,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,7376,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,5879,+r,-Wr,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,1471,+r,+Wr,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,0,Dcpu=4130:61400 in  Dcpu=4130:61400 : unknown key Dcpu. 
** Error in 9,h,0,Dpst=4750,58490,11100,20,690,64680 in  Dpst=4750 : unknown key Dpst. ** Error in 9,h,0,Dpst=4750,58490,11100,20,690,64680 in  58490 : unknown key 58490. ** Error in 9,h,0,Dpst=4750,58490,11100,20,690,64680 in  11100 : unknown key 11100. ** Error in 9,h,0,Dpst=4750,58490,11100,20,690,64680 in  20 : unknown key 20. ** Error in 9,h,0,Dpst=4750,58490,11100,20,690,64680 in  690 : unknown key 690. ** Error in 9,h,0,Dpst=4750,58490,11100,20,690,64680 in  64680 : unknown key 64680. 
** Error in 9,h,6,-Wr,Est=127 in  Est=127 : unknown key Est. 
** Error in 9,h,56,-r,Est=98 in  Est=98 : unknown key Est. 
** Error in 9,h,17,Est=101 in  Est=101 : unknown key Est. 
** Error in 9,h,0,+Etw=136 in  +Etw=136 : unknown key Etw. 
** Error in 9,h,400,+Eal=102 in  +Eal=102 : unknown key Eal. 
** Error in 9,h,0,+Eal=119 in  +Eal=119 : unknown key Eal. 
** Error in 9,h,35,Esw=138 in  Es : unknown key Es. 
** Error in 9,h,4,-Eal=102 in  -Eal=102 : unknown key Eal. 
** Error in 9,h,1,+S,+Eal=140 in  +Eal=140 : unknown key Eal. 
** Error in 9,h,27,+Eal=141 in  +Eal=141 : unknown key Eal. 
** Error in 9,h,0,+Eal=142 in  +Eal=142 : unknown key Eal. 
** Error in 9,h,0,+Eal=143 in  +Eal=143 : unknown key Eal. 
** Error in 9,h,1,+Eal=144 in  +Eal=144 : unknown key Eal. 
** Error in 9,h,5,Sb=1,-Eal=140 in  -Eal=140 : unknown key Eal. 
** Error in 9,h,11,-Eal=119 in  -Eal=119 : unknown key Eal. 
** Error in 9,h,15,-Eal=142 in  -Eal=142 : unknown key Eal. 
** Error in 9,h,7,-Eal=143 in  -Eal=143 : unknown key Eal. 
** Error in 9,h,1,-Eal=144 in  -Eal=144 : unknown key Eal. 
** Error in 9,h,78,-Eal=141 in  -Eal=141 : unknown key Eal. 
** Error in 9,h,426,-Ws,Est=95 in  Est=95 : unknown key Est. 
** Error in 9,h,86,Pss=1,-Etw=136 in  -Etw=136 : unknown key Etw. 
** Error in 9,h,5410,+Eal=141 in  +Eal=141 : unknown key Eal. 
** Error in 9,h,99,-Eal=141 in  -Eal=141 : unknown key Eal. 
** Error in 9,h,90,-Wm,Est=95 in  Est=95 : unknown key Est.

**Comment by kwadkore** [comment]
The recent update now parses these keys.
