### ISSUE TITLE
Failed to run: go run setup.go 

### ISSUE THREAD

**Issue by luobo25** [google/battery-historian#52]
I get following messages:
```
 ~/works/go/src/github.com/google/battery-historian$ go run setup.go
# github.com/golang/protobuf/proto
../../golang/protobuf/proto/text.go:39: imported and not used: "encoding"
../../golang/protobuf/proto/text.go:538: undefined: encoding
../../golang/protobuf/proto/text.go:800: undefined: encoding
../../golang/protobuf/proto/text_parser.go:38: imported and not used: "encoding"
../../golang/protobuf/proto/text_parser.go:861: undefined: encoding
```

The operating system is Ubuntu 12.04.  I have tried go1.6 and go1.5.3. Both are the same. And it works fine on my mac.

**Comment by pkufergus** [comment]
run go get -u github.com/golang/protobuf/{proto,protoc-gen-go},
then i can compile pass

**Comment by luobo25** [comment]
Sadly, i still get the similar error...
```
$ go get -u github.com/golang/protobuf/{proto,protoc-gen-go} 
../../golang/protobuf/proto/text.go:39:2: no Go source files in /usr/lib/go/src/pkg/encoding
```

**Comment by HongJungSon** [comment]
I had the same problem, but after updating with the latest go, problem resolved.

**Comment by shanwu** [comment]
Yeah, I got the same issue too. 
At first, I downloaded and installed go by apt-get function from Ubuntu, 
and I got these errors when compiling.  
I solve this issue by following the go installation instruction from [provided link](https://golang.org/doc/install).
