### ISSUE TITLE
json: unsupported value: NaN

### ISSUE THREAD

**Issue by awenger** [google/battery-historian#54]
I installed battery-historian successfully . However uploading a bugreport leads to `json: unsupported value: NaN`

```
2016/03/30 12:15:18 Listening on port:  9999
2016/03/30 12:15:30 Trace starting analysisServer processing for: GET
2016/03/30 12:15:30 Trace finished analysisServer processing for: GET
2016/03/30 12:15:30 Trace starting analysisServer processing for: GET
2016/03/30 12:15:30 Trace finished analysisServer processing for: GET
2016/03/30 12:15:36 Trace starting analysisServer processing for: POST
2016/03/30 12:15:36 Trace starting reading uploaded file. 13902706 bytes
2016/03/30 12:15:37 Trace started analyzing file.
2016/03/30 12:15:37 Trace finished processing summary data.
2016/03/30 12:15:37 Trace finished generating Historian plot.
2016/03/30 12:15:37 Trace finished processing checkin.
2016/03/30 12:15:38 Trace finished generating Historian plot and summaries.
2016/03/30 12:15:39 Trace ended analyzing file.
2016/03/30 12:15:39 Trace finished analysisServer processing for: POST
```

The Bugreport was taken with `adb bugreport > bugreport_a.txt` and this is my go version: `go version go1.2.1 linux/amd64`

**Comment by xiaoliang2016** [comment]
I have the same problem,any one can resolve it?

**Comment by Denis10** [comment]
I have the same

**Comment by ajrocks** [comment]
Same here

**Comment by 1993hzw** [comment]
I have the same

**Comment by youshuchang** [comment]
I have the same

**Comment by Muse1021** [comment]
Who can resolve it?

**Comment by bowenYu** [comment]
Same here

**Comment by derlio** [comment]
same here

**Comment by vlahan** [comment]
Same here, but the problem started when reset the battery stats and enabled full-wake-history

**Comment by kwadkore** [comment]
We've updated Historian to prevent this issue.

**Comment by tauntz** [comment]
I'm still seeing this happen to about 20% of the bugreports that I generate on-device.
Running battery historian with:
`docker run -p 8888:9999 gcr.io/android-battery-historian/stable:3.0 --port 9999`

Shall I open a new issue for this?

**Comment by xfmax** [comment]
you must execute "adb shell dumpsys batterystats --enable full-wake-history",then execute "adb shell dumpsys batterystats --reset",guarantee the order in which  command execute！
