### ISSUE TITLE
Could not analyze bug report generated on Android N Preview

### ISSUE THREAD

**Issue by KeithYokoma** [google/battery-historian#58]
When I posted a bug report generated on Android N Preview, Battery Historian just stopped working with the following log and the UI stayed at "Analyzing..." status.

Any report format changes introduced in Android N?

```
2016/04/26 17:30:15 Listening on port:  9999
2016/04/26 17:30:18 Trace starting analysisServer processing for: GET
2016/04/26 17:30:18 Trace finished analysisServer processing for: GET
2016/04/26 17:30:19 Trace starting analysisServer processing for: GET
2016/04/26 17:30:19 Trace finished analysisServer processing for: GET
2016/04/26 17:30:24 Trace starting analysisServer processing for: POST
2016/04/26 17:30:24 Trace starting reading uploaded file. 22327437 bytes
2016/04/26 17:30:24 Trace started analyzing file.
2016/04/26 17:30:25 Trace finished generating Historian plot.
```

**Comment by bowenYu** [comment]
I encountered the same problem. My device is Meizu Pro 5, android version 5.1.

**Comment by bhaavanmerchant** [comment]
Yes, I am facing the same issue. The UI is at "Analyzing" status, and the console reads :
```
2016/05/10 17:12:23 Trace starting reading uploaded file. 14156608 bytes
2016/05/10 17:12:24 Trace started analyzing file.
2016/05/10 17:12:25 Trace finished generating Historian plot.
```

**Comment by kwadkore** [comment]
Can you share the bug report please?

**Comment by jacobajit** [comment]
Same issue, UI stuck at analyzing

**Comment by bhaavanmerchant** [comment]
@kwadkore My bug report had a `Exception occurred while dumping`. Which caused it to enter the if condition on line 626 in `analyser.go`. But it never logged the error in its console. I have raised a PR #60 which will atleast show this issue on the go console.
Ideally however, the close function must also redirect the browser to homepage with the error message.

**Comment by jacobajit** [comment]
Taking out one line from the bug report seems to work https://www.reddit.com/r/AndroidPreviews/comments/4ixgud/google_battery_historian_doesnt_work_with_android/

**Comment by kwadkore** [comment]
The server got stuck at line 682. We've updated the code to handle errors better.
