### ISSUE TITLE
Slight change to error message for when closure-compiler ZIP can't be downloaded

### ISSUE THREAD

**Issue by jeremyhill-up** [google/battery-historian#66]
I'm behind a corporate proxy which does all kinds of nasty things, so I get this:

>
C:\...\src\github.com\google\battery-historian>go run setup.go
>
Downloading Closure compiler...
Failed to download Closure compiler: Get http://dl.google.com/closure-compiler/compiler-20160208.zip: dial tcp 198.70.248.227:80: i/o timeout
>
If this persists, please manually download the compiler from http://dl.google.com/closure-compiler/compiler-20160208.zip into the C:\...\src\github.com\google\battery-historian/third_party/closure-compiler directory, unzip it into the C:\...\src\github.com\google\battery-historian/third_party/closure-compiler diretory, and rerun this script.

Looking in the go script, it expects the ZIP file to be there, not to be unzipped/extracted:

````
	_, errF := os.Stat(path.Join(closureCompilerDir, closureCompilerZip))
	if os.IsNotExist(errD) || os.IsNotExist(errF) {
		fmt.Println("\nDownloading Closure compiler...")
````

  So I'd change the wording a bit later on to:
>
fmt.Printf("\nIf this persists, please manually download the compiler from %s, place it into the %s directory, and rerun this script.\n\n", closureCompilerURL, closureCompilerDir, closureCompilerDir)

I'd submit a pull request but I'm honestly too dumb to know how to do that.

**Comment by kwadkore** [comment]
The script expects that if the ZIP file is in the directory, then it has also been unzipped. Battery Historian will not run properly without the unzipped contents. The ZIP file is just a marker for the setup script to know whether to download/update the compiler contents. The script won't unzip the file if the file is already in the directory, so the wording is correct.
