### ISSUE TITLE
README doesn't exist

### ISSUE THREAD

**Issue by seato** [google/battery-historian#7]
A README would be a nice addition to this repository now that this lib is picking up ground.

**Comment by vbauer** [comment]
:+1:

**Comment by paulirish** [comment]
Screenshot for the readme:

![image](https://cloud.githubusercontent.com/assets/39191/6672879/846e44ae-cbcc-11e4-9fc3-7805143fc3ac.png)

**Comment by MarcusWolschon** [comment]
There is one VERY important information that isn't conveyed to the developer:
What minimum Android version is required for the mentioned 
" # adb shell dumpsys batterystats"

Everyone analysing battery performance on phones older then this, shouldn't even have to spend time trying to figure out if this project is actually a usable tool for him/her.
(https://developer.android.com/about/versions/android-5.0.html
 aparently it's not supported on Android 4.0.4 and 4.1 so if your phone will never get a 5.0 update, you're out of luck.)

**Comment by paulirish** [comment]
[Colt’s Super Unofficial Guide to Getting started with Battery Historian](https://docs.google.com/document/d/1CSTRAaCtbjTe2rs2vzra6-PViMkfPJC9DVWg7NbXqYk/edit#heading=h.6ktierq5a3p5)

**Comment by tjohns** [comment]
This was fixed with the Battery Historian 2.0 release at Google I/O.
