### ISSUE TITLE
Last command is not working

### ISSUE THREAD

**Issue by Ledig** [google/battery-historian#77]
I followed the above tutorial and every step is fine until I reached the last one.

While I executed the last step 

>python historian.py batterystats.txt > batterystats.html

It gives me an error as 
File "Historian.py", Line xx
print "\nUsage: %s [OPTIONS] [FILE]\n" %sys.argv[0]
SyntaxError: Missing parenthesis in call to 'print'

The file of batterystats.txt is being generated but batterystats.html is not being created

Am using Python 3.5.2

**Comment by kwadkore** [comment]
Historian uses Python 2.7.
