### ISSUE TITLE
Bugreport overflow

### ISSUE THREAD

**Issue by amnonjw** [google/battery-historian#81]
Hello experts.

I started using the battery-historian to analyze the activities of my Nexus 5x over night. after several times of producing the bugreport and analyzing, I now get the following notification when I open a new reports:

Battery history log overflow has been detected for the uploaded bugreport. Please note analysis should not be entirely trusted due to overflow.

The time curves I get are half empty, and they start from over a day back. Last night before going to sleep I tried running
`adb logcat -c`
in my cmd prompt but today I saw that it didn't have any effect.

restarting the device also didn't help.

Do you have any idea what to do?

**Comment by anisart** [comment]
To reset aggregated battery stats and history:

```
adb shell dumpsys batterystats --reset
```

from README.MD
