### ISSUE TITLE
can not found the submit button

### ISSUE THREAD

**Issue by CaoPeng** [google/battery-historian#83]
configure the battery-historian step by step via README
battery-historian has configured successful (http://localhost:9999)
However, the submit button was disappeared 

does anybody fixed this issue?
Could you help me to fix this issue?

**Comment by ozaryx** [comment]
Submit button appear when you added bugreport for load

**Comment by CaoPeng** [comment]
@ozaryx Thanks your feedback.
We'd better share more info as below:
**command line output:**
2016/09/21 10:46:22 Listening on port:  9999
2016/09/21 10:46:44 Trace starting analysisServer processing for: GET
2016/09/21 10:46:44 Trace finished analysisServer processing for: GET
2016/09/21 13:48:44 Trace starting analysisServer processing for: GET
2016/09/21 13:48:45 Trace finished analysisServer processing for: GET
click **Browser** icon to try to select the bugreport.txt file,and then click *Open* button at 10:46.
waiting.....waiting....waiting.... Submit button does not appear!

**Comment by fengguoqing** [comment]
@CaoPeng  the cause maybe is you can't access Google network, because some resource get from Google serve, you could instead with domestic address.

**Comment by ozaryx** [comment]
@CaoPeng In my case Submit button apper fast enough. Probably you using proxy, check availability Google services.
In the page source there is a string <script src="//www.gstatic.com/external_hosted/jquery_form/jquery.form.min.js" charset="utf-8"></script>

**Comment by CaoPeng** [comment]
@fengguoqing 
I can access Google successful(XX-Net). add lots of rules to XX-Net proxy
Could you please share me that how do we instead with domestic?
Could you please share you WeChat ID?(**sirCao** --> my WeChart ID)

@ozaryx 
Thanks, I will check it.
Could you please leave your email address?

**Comment by CaoPeng** [comment]
BTW:
@fengguoqing  & @ozaryx 
http://23.251.148.173/ --> this address looks like was depolyed the Battery Historian.
However ,submit button does not appear ..

**Comment by ozaryx** [comment]
@CaoPeng ozaryx@gmail.com

**Comment by ozaryx** [comment]
@CaoPeng & @fengguoqing 
Whitout internet connection battery-historian not work at all.

**Comment by fengguoqing** [comment]
@CaoPeng please observe bottom left corner of web, is there hint that accessing gstatic.com?

**Comment by CaoPeng** [comment]
@ozaryx & @fengguoqing 
I can access gstatic.com directly.(http://www.gstatic.com/external_hosted/jquery_form/jquery.form.min.js)

What's below message means? 
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:14321/compiled/historian-optimized.js?ver=1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:14321/third_party/flot-axislabels/jquery.flot.axislabels.js?ver=1 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:14321/compiled/historian-optimized.js?ver=1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by Joeluck** [comment]
Hello, 

Exact same problem here, any news to help us correct this issue ?

**Comment by CaoPeng** [comment]
Thanks everyone.
already resolved this issue.
this issue may caused by GFW(what's a f***k).
- use VPN
- replace the public library(.js) from Google provider to native(such as http://lib.sinaapp.com/)

**Comment by QingShiLuoGu** [comment]
Chrome 103.0.5060.66 fail, IE success.
