### ISSUE TITLE
Does not accept bugreport

### ISSUE THREAD

**Issue by Zeklandia** [google/battery-historian#90]
It says `bugreport.txt does not contain a valid bugreport file` when I upload [this file](https://www.dropbox.com/s/fu2jlz9dns67xqh/bugreport.txt?dl=0).

**Comment by tekkasit** [comment]
I think in bugreport format is tweaked in Android 7.1, See bug #89 .

**Comment by Zeklandia** [comment]
That must have been it.

**Comment by bhadkiaftab** [comment]
remove > from command

**Comment by bhadkiaftab** [comment]
adb bugreport > Desktop/lokt.zip .     remove > and try

**Comment by SleepySleeperson** [comment]
Thanks. It worked.
